"""
Shared plotting style + data loading for the figures in docs/images/.

Every figure is generated by its own script in tools/ and every script writes a
light and a dark PNG, because the README serves them through
<picture media="(prefers-color-scheme: dark)">.

Depends only on numpy + matplotlib (requirements-plot.txt) -- nothing here
touches AEDT, so the figures can be regenerated from committed CSVs alone.
"""
import glob
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ----------------------------------------------------------------------
# Model constants -- must match magnetic_field_wire.py
# ----------------------------------------------------------------------
MU0 = 4e-7 * np.pi
CURRENT = 5.0          # A
WIRE_LENGTH = 50e-3    # m
WIRE_RADIUS_MM = 2.0   # mm
R_START_MM = 3.0       # first point of Extraction_Line
R_END_MM = 20.0        # last point of Extraction_Line

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(REPO, "results")
IMAGES = os.path.join(REPO, "docs", "images")

# Categorical slots 1-3 of the reference palette, light / dark steps.
THEMES = {
    "light": dict(
        surface="#fcfcfb", primary="#0b0b0b", secondary="#52514e",
        muted="#8b8a85", grid="#e4e3df",
        series=("#2a78d6", "#eb6834", "#1baf7a"),
        # One-hue sequential ramp (blue), light -> dark, for ordered sweeps.
        ramp=("#86b6ef", "#5598e7", "#3987e5", "#256abf", "#104281"),
    ),
    "dark": dict(
        surface="#1a1a19", primary="#ffffff", secondary="#c3c2b7",
        muted="#8b8a85", grid="#333331",
        series=("#3987e5", "#d95926", "#199e70"),
        ramp=("#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#184f95"),
    ),
}
MODES = ("light", "dark")


# ----------------------------------------------------------------------
# Analytic magnetostatics
# ----------------------------------------------------------------------
def b_infinite(r_mm):
    """Ampere's law for an infinitely long wire: B = mu0*I / (2*pi*r), in uT."""
    r = np.asarray(r_mm, dtype=float) * 1e-3
    return MU0 * CURRENT / (2 * np.pi * r) * 1e6


def b_finite(r_mm):
    """
    Biot-Savart for a straight segment of length L, on its midplane:

        B = mu0*I*L / (2*pi*r*sqrt(L^2 + 4*r^2))

    Reduces to the infinite-wire result as L -> infinity. In uT.
    """
    r = np.asarray(r_mm, dtype=float) * 1e-3
    return (
        MU0 * CURRENT * WIRE_LENGTH
        / (2 * np.pi * r * np.sqrt(WIRE_LENGTH**2 + 4 * r**2))
    ) * 1e6


def b_inside(r_mm):
    """
    Inside a solid conductor of radius a carrying a uniform current density,
    Ampere's law encloses only the fraction (r/a)^2 of the current:

        B = mu0*I*r / (2*pi*a^2)

    So |B| rises linearly from 0 on the axis to the surface value. In uT.
    """
    r = np.asarray(r_mm, dtype=float) * 1e-3
    a = WIRE_RADIUS_MM * 1e-3
    return MU0 * CURRENT * r / (2 * np.pi * a**2) * 1e6


def finite_length_factor(r_mm):
    """b_finite / b_infinite = L / sqrt(L^2 + 4 r^2). Dimensionless."""
    r = np.asarray(r_mm, dtype=float) * 1e-3
    return WIRE_LENGTH / np.sqrt(WIRE_LENGTH**2 + 4 * r**2)


# ----------------------------------------------------------------------
# Solver output
# ----------------------------------------------------------------------
def load_csv(path):
    """
    r [mm], |B| [uT] from an AEDT trace export.

    The export is semicolon-separated with a 'Distance [mm]' column measured
    from the start of Extraction_Line, so r = R_START_MM + Distance.
    """
    d = np.genfromtxt(path, delimiter=";", names=True, encoding="utf-8")
    distance_mm = d[d.dtype.names[0]]
    b_tesla = d[d.dtype.names[1]]
    return R_START_MM + distance_mm, b_tesla * 1e6


def load_baseline():
    return load_csv(os.path.join(RESULTS, "B_Field_Data.csv"))


def load_sweep(subdir, prefix):
    """
    Load a parameter study written by studies/*.py as
    results/<subdir>/<prefix><value>.csv, one file per swept value.

    Returns [{"value", "r", "b", "meta"}, ...] sorted by value, or [] if the
    study has not been run yet. "meta" is the sidecar JSON the study wrote
    (element counts, region size), or {} if there isn't one.
    """
    pattern = os.path.join(RESULTS, subdir, prefix + "*.csv")
    out = []
    for path in glob.glob(pattern):
        stem = os.path.splitext(os.path.basename(path))[0]
        try:
            value = float(stem[len(prefix):])
        except ValueError:
            continue
        r, b = load_csv(path)
        meta_path = os.path.splitext(path)[0] + ".json"
        meta = {}
        if os.path.exists(meta_path):
            with open(meta_path, encoding="utf-8") as fh:
                meta = json.load(fh)
        out.append(dict(value=value, r=r, b=b, meta=meta))
    return sorted(out, key=lambda case: case["value"])


def at_radius(r_mm, b_uT, target_mm):
    """|B| interpolated at one radius."""
    return float(np.interp(target_mm, r_mm, b_uT))


# ----------------------------------------------------------------------
# Style
# ----------------------------------------------------------------------
def style(fig, axes, t):
    fig.patch.set_facecolor(t["surface"])
    for ax in np.atleast_1d(axes).ravel():
        ax.set_facecolor(t["surface"])
        ax.tick_params(colors=t["secondary"], labelsize=9, length=3, width=0.8)
        ax.xaxis.label.set_color(t["secondary"])
        ax.yaxis.label.set_color(t["secondary"])
        for side in ("top", "right"):
            ax.spines[side].set_visible(False)
        for side in ("left", "bottom"):
            ax.spines[side].set_color(t["grid"])
            ax.spines[side].set_linewidth(0.8)
        ax.grid(True, color=t["grid"], linewidth=0.8, alpha=0.9)
        ax.set_axisbelow(True)


def title(ax, text, t, sub=None):
    ax.set_title(text, color=t["primary"], fontsize=12, loc="left", pad=10)
    if sub:
        ax.annotate(
            sub, xy=(0, 1.0), xytext=(0, 14), xycoords="axes fraction",
            textcoords="offset points", fontsize=9, color=t["secondary"],
        )


def legend(ax, t, loc="upper right", **kw):
    leg = ax.legend(frameon=False, fontsize=9, loc=loc, handlelength=1.6, **kw)
    for txt in leg.get_texts():
        txt.set_color(t["secondary"])
    return leg


def linear_ticks(ax):
    """Plain numbers on a log |B| axis -- '10^2' tells a reader nothing here."""
    ax.yaxis.set_major_formatter(matplotlib.ticker.ScalarFormatter())
    ax.yaxis.set_minor_formatter(matplotlib.ticker.NullFormatter())


def caption(fig, text, t, x=0.11, y=0.015):
    fig.text(x, y, text, fontsize=8, color=t["muted"])


def save(fig, name, mode, t):
    os.makedirs(IMAGES, exist_ok=True)
    suffix = "" if mode == "light" else "-dark"
    path = os.path.join(IMAGES, f"{name}{suffix}.png")
    fig.savefig(path, dpi=160, facecolor=t["surface"])
    plt.close(fig)
    print(f"wrote {os.path.relpath(path, REPO)}")


def missing(study, script):
    print(f"skipped {study}: no CSVs yet -- run `python {script}` in AEDT first")
